set(hci_rpmsg_KERNEL_HEX_NAME zephyr.hex)
set(hci_rpmsg_ZEPHYR_BINARY_DIR C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr)
set(hci_rpmsg_KERNEL_ELF_NAME zephyr.elf)
list(APPEND hci_rpmsg_BUILD_BYPRODUCTS C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr/zephyr.hex)
list(APPEND hci_rpmsg_BUILD_BYPRODUCTS C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr/zephyr.elf)
set(CPUNET_PM_DOMAIN_PARTITIONS C:/Users/Jacob/Desktop/test2/hci_rpmsg/partitions_CPUNET.yml)
set(CPUNET_PM_DOMAIN_REGIONS C:/Users/Jacob/Desktop/test2/hci_rpmsg/regions_CPUNET.yml)
set(CPUNET_PM_DOMAIN_HEADER_FILES C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr/include/generated/pm_config.h)
set(CPUNET_PM_DOMAIN_IMAGES CPUNET:hci_rpmsg)
set(CPUNET_PM_HEX_FILE C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr/merged_CPUNET.hex)
set(CPUNET_PM_DOTCONF_FILES C:/Users/Jacob/Desktop/test2/hci_rpmsg/pm_CPUNET.config)
set(CPUNET_PM_APP_HEX C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr/app.hex)
set(CPUNET_PM_SIGNED_APP_HEX C:/Users/Jacob/Desktop/test2/hci_rpmsg/zephyr/signed_by_b0_app.hex)
